- buildbot_nix/__init__.py
- buildbot_nix/github_projects.py
- nix/worker.nix
see commit messages, happy to clarify if anything is unclear :)
> small fixes

- default.nix
- flake.lock
- flake.nix
- nix/master.nix
- pyproject.toml
fixed in nixpkgs in https://nixpk.gs/pr-tracker.html?pr=263963
We still need to wait for the PR to hit nixpkgs-unstable.
> drop setuptools from PYTHONPATH

- README.md
Since not everyone will know what it is.
> doc: add link to buildbot

- README.md
- examples/master.nix
Ran into this with @lorenzleutgeb while setting up Buildbot to use Cachix.
> examples: Fix typos in Cachix example

- buildbot_nix/gitea_projects.py
> Fix Gitea backend not authenticating properly with Gitea

- nix/master.nix
partial revert of b2ed2ccacc6d0a890c97165cd11aa2390b07d393
> remove boot workaround

- nix/master.nix
This is getting slightly silly, here's me hoping this is the last "Cachix fix" PR...
To that end, I used the following truth table to generate the assertion expression:
[link](https://tma.main.jp/logic/logic.php?lang=en&type=3&v0=a&v1=b&v2=c&00=1&01=1&02=0&03=1&04=0&05=1&06=0&07=1)
Where `a`, `b` are the expressions `cfg.cachix.authTokenFile == null` and `cfg.cachix.signingKeyFile == null`, their ordering is meaningless. `c` is `cfg.cachix.enable`. Which leads us to the expression:
```nix
isNull cfg.cachix.authTokenFile && isNull cfg.cachix.signingKeyFile ||
isNull cfg.cachix.authTokenFile && cfg.cachix.enable ||
isNull cfg.cachix.signingKeyFile && cfg.cachix.enable;
```
This catches cases where the user has Cachix enabled but doesn't set `cfg.cachix.enable` to `true`. I've done extensive …
> Actually fix Cachix, attempt 3

- nix/treefmt/flake-module.nix
this fixes the project with juju or other git alternatives.
> use LICENSE.md for project root detection in flake-module.nix

- buildbot_nix/__init__.py
- buildbot_nix/models.py
- nix/master.nix
@zowoq this PR actually fixes cachix, I stubbed out the cachix binary (shell script in my case) and confirmed the correct secrets make it into its environment. Please test.
> Properly fully fix Cachix

- buildbot_nix/__init__.py
- buildbot_nix/gitea_projects.py
- buildbot_nix/github_projects.py
- buildbot_nix/projects.py
> Fix missing information in build names

- buildbot_nix/__init__.py
https://github.com/nix-community/buildbot-nix/pull/243
> Revisited: feat!: Update output path writing

- buildbot_nix/__init__.py
> url quote all paths when updating build output paths

- nix/master.nix
https://buildbot.thalheim.io/nix-outputs/
Adding this:
```
extraConfig = ''
charset utf-8;
autoindex on;
'';
```
https://buildbot.nix-community.org/nix-outputs/
> fix outputsPath nginx config

- buildbot_nix/__init__.py
according to twisted documentation, this should work?
> [total untested] async syntax

- buildbot_nix/__init__.py
- buildbot_nix/nix_status_generator.py
- flake.nix
> Allows restarting individual builds

- buildbot_nix/failed_builds.py
- flake.lock
- nix/master.nix
- nix/treefmt/flake-module.nix
- pyproject.toml
https://nixpkgs-tracker.ocfox.me/?pr=348410
> buildbot 4.1.0

- buildbot_nix/buildbot_nix/oauth2_proxy_auth.py
Taken from https://github.com/nix-community/buildbot-nix/pull/350
> oauth2_proxy_auth: fix type check

- buildbot_nix/buildbot_nix/__init__.py
Found in https://github.com/nix-community/buildbot-nix/issues/352
> require to define at least one worker

- buildbot_nix/buildbot_nix/__init__.py
this was introduced in f5f907d0
> add missing return

- buildbot_nix/buildbot_nix/__init__.py
- buildbot_nix/buildbot_nix/nix_status_generator.py
- flake.lock
- flake.nix
Even in the current NixOS release we ship 4.1
> BuildRequestModel and BuildModel are no longer dicts

- buildbot_nix/buildbot_nix/__init__.py
otherwise we will get progressbars, we don't want
> undo `usePTY`

- buildbot_nix/buildbot_nix/__init__.py
remove unnecessary environment logging and enable lazy logfiles on command where we don't expect any output
> speed up some build steps

- buildbot_nix/buildbot_nix/oauth2_proxy_auth.py
- examples/default.nix
- flake.lock
Fixes the issues blocking #395
> flake: bump Nixpkgs

- buildbot_nix/buildbot_nix/__init__.py
- nix/packages.nix
> Skip builds fully to avoid delays from worker setup

- README.md
fixes https://github.com/nix-community/buildbot-nix/issues/424
> README: document Incompabilities with the lix overlay

- .github/workflows/update-flake-lock.yml
Seems `buildbot-nix-ci` app was already set up for this repo and just needs to be added to the action.
> .github/workflows/update-flake-lock.yml: merge automatically

- nixosModules/master.nix
> :bug: add openssh to master node

- buildbot_nix/buildbot_nix/repo_config/__init__.py
- flake.lock
- nixosModules/master.nix
- packages/buildbot.nix
https://nixpkgs-tracker.ocfox.me/?pr=406602
> buildbot 4.3
