flake.nix
The `buildbot` branch has been merged and doesn't exist in the `Mic92/nixpkgs` repository anymore
=> revert back to mainline nixpkgs

.github/dependabot.yml, .github/workflows/update-flake-lock.yml, examples/default.nix, flake.lock, flake.nix, nix/0001-allow-secrets-to-be-group-readable.patch, nix/checks/master.nix, nix/master.nix, nix/worker.nix
This fixes force push where github doesn't return the latest ref although the webhook event is already fired.
=> add patch to make systemd LoadCredential work again

buildbot_nix/__init__.py
```
https://buildbot.nix-community.org//change_hook/github
```
Noticed this when I checked the webook that was created in `nix-community/infra`.
=> remove extra slash from webhook url

buildbot_nix/__init__.py
This doesn't invoke nix-instantiate anymore, but
`nix-eval-jobs --flake .#checks`.
=> buildbot_nix: update comment

buildbot_nix/__init__.py
So far we cannot have builds running concurrently, whereas we only would need to be strict about nix evaluation to stay below memory limits.
=> relax concurrent builds

buildbot_nix/__init__.py, buildbot_nix/github_projects.py
This way errors are more visible to users on the first running.
=> only refresh github projects in timer and sort them

buildbot_nix/__init__.py, buildbot_nix/common.py, buildbot_nix/gitea_projects.py, buildbot_nix/github_projects.py, buildbot_nix/projects.py, buildbot_nix/secrets.py, buildbot_nix/util.py, examples/master.nix, nix/buildbot-gitea.nix, nix/checks/master.nix, nix/master.nix
This pull request is just there to publicize the code I'm working on, before being ready it'll get probably more cleaned up and merged with the Gitea backend pull request.
=> Add support for Gitea

nix/master.nix
In some CI setups (especially those where the CI server is reachable over a VPN with split-horizon DNS), the URL to access the CI server differs from the URL that the (external) webhook endpoint listens on. 
This change introduces an option webhookBaseUrl that allows setting that URL independently from the buildbot installation URL.
=> Make the webhook endpoint URL configurable

examples/master.nix, nix/master.nix
Let me preface this by saying I'm new to Nix, so sorry if I've missed something obvious and there's another way around this. Also, thank you for your work on this module!
I'm setting up  a buildbot instance using buildbot-nix and I ran into a usecase that isn't currently handled by the module. My buildbot is behind a third party proxy that does TLS termination for me, so I don't need nginx to create or serve any certificates, but there's no way to let the module know that the endpoint must start with `https://` because this is currently tied to the nginx configuration. This patch adds a config option to make the endpoint use `https://` even if it's not setup in nginx.
=> master: Add config to force https for the endpoint

nix/master.nix
https://github.com/nix-community/infra/pull/1235#discussion_r1590512432
Seems this needs to be always instead of on-failure as the service exits successfully.
=> master: on-failure -> always

buildbot_nix/github/installation_token.py
Fixes not properly renewing the `InstallationToken` when using the GitHub App backend. Observed on my private instance.
=> Fix GitHub `InstallationToken` renewal.

buildbot_nix/github/jwt_token.py
Fixes #184, tested by running the following script for 8 hours and creating 360 builds over two repos:
```bash
#!/usr/bin/env bash
set -x -e -o pipefail
for repo in *; do
[ -d "$repo" ] && (
cd "$repo"
git config --local user.name 'test'
git config --local user.email 'test@example.com'
git commit --allow-empty --m 'test'
GIT_SSH_COMMAND='ssh -F/dev/null -i .git/id_ed25519 -o IdentitiesOnly=yes' git push origin
)
done
```
=> Fix JWT token renewal condition

README.md, examples/attic-watch-store.nix
This is a simple but working systemd service to upload the contents of the local buildbox-nix store to an attic cache, for use my other machines/nodes.
=> Added simple attic watch store example

buildbot_nix/__init__.py, buildbot_nix/common.py, buildbot_nix/gitea_projects.py, buildbot_nix/github/installation_token.py, buildbot_nix/github_projects.py, buildbot_nix/projects.py
Defers hook creation to project reload time, adds another `BuildStep` to each reload `buildset` which creates hooks for all loaded projects. As a side effect, filters repositories by tag, before writing them to the cache file, keeps load-time filter to not break existing deployments.
=> Defer hook creation to project reload, both GitHub and Gitea

LICENSE.md
the license was already in the pyproject.toml file but github likes to
have files instead
=> add missing license file

buildbot_nix/__init__.py, nix/0001-GiteaHandler-set-the-category-of-PR-changes-to-pull-.patch, nix/0002-GiteaHandler-set-branch-to-the-PR-branch-not-the-bas.patch, nix/master.nix
~Very WIP, problem is that I tried to execute the registering in the skipped builder in the master, which needed the gcroots directory to be writable by both. the master and workers. But POSIX file permissions had a different idea and ruined my evening. I'll have to trigger the registration on a different builder...~
Works by adding a new builder, `project-nix-register-gcroot` which is triggered from both the `project-nix-build` and `project-nix-skipped-build` builders. That allows to always run the gcroot creation on the workers and avoids any permission issues. To keep `nix-skipped-build` performant, the check whether to do gcroot registration or not is done using OS primitives and is not done in a separate worker or buildstep.
=> Register gcroots for PRs

nix/master.nix
Catches a breaking change that silently disables Cachix on existing deployments. @Mic92 please merge ASAP, should have went in with #231 but I thought of this 5 minutes ago.
=> Add check, which catchis silent disabling of cachix

buildbot_nix/__init__.py, buildbot_nix/common.py, buildbot_nix/gitea_projects.py, buildbot_nix/github_projects.py, buildbot_nix/models.py, nix/master.nix
This PR adds two derived classes `ModifyingGitHubStatusPush` and `ModifyingGiteaStatusPush`, which take the `modifyingFilter` argument. It has the type `Callable[[Any], Any | None]`, if it returns `None` the report is canceled, if it returns non `None` the returned object is used instead of the original.
We use this addition to implement "combined builds", if the jobs count for a `nix-eval` is over a certain number (made to be configurable in a future rendition of this PR) `buildbot-nix` will not create reports on GitHub for each build, but only a single `nix-build-combined` report which indicates whether all builds succeeded or failed.
~~This PR is also a draft because it is built for buildbot 3, as with #216 I first need to bump my instance to 4. I'll make a separate patch for 3 and 4 …
=> Combined build reports GitHub

README.md, buildbot_nix/__init__.py, buildbot_nix/models.py, buildbot_nix/oauth2_proxy_auth.py, examples/default.nix, examples/fully-private-github.nix, nix/master.nix
This places `oauth2-proxy` in front of buildbot and protects the whole instance unconditionally. Buildbot doesn't really support hiding information currently, the websocket is completely unauthenticated and leaks information left and right, therefore a proxy is necessary.
=> Support fully private mode

buildbot_nix/github_projects.py, nix/master.nix
This should fix handling PRs, as reported by @Mic92:
```
Failed fetching PR commit message: response code 401: b'{"message":"Bad credentials","documentation_url":"[https://docs.github.com/rest","status":"401](https://docs.github.com/rest%22,%22status%22:%22401)"}'
```
=> Use installation tokens for GitHub change hooks

buildbot_nix/models.py, examples/master.nix, nix/checks/master.nix
I think this is might be fixed but I'll test it in a couple of hours to make sure.
```
❯ nix eval .#nixosConfigurations.example-cachix-master-worker-combined-x86_64-linux.config.systemd.services.buildbot-master.serviceConfig.LoadCredential
[ "buildbot-nix-workers:/nix/store/zjhcahczn8b64kw90bbxzhlvw5smm0vi-workers.json" "github-webhook-secret:/nix/store/svaxdh1zss9jgs7365s601gxprg633jv-webhookSecret" "github-app-secret-key:/nix/store/z3yssjnmvpp3vfbyr7i7r8f3qfqgydc1-app-secret.key" "github-oauth-secret:/nix/store/jbvsw789q8g1a23cc9qvq5jhf14mf8v2-oauthSecret" ]
```
```
❯ nix eval .#nixosConfigurations.example-cachix-master-worker-combined-x86_64-linux.config.systemd.services.buildbot-master.serviceConfig.LoadCredential
[ "buildbot-nix-workers:/nix/store/zjhcahczn8b64kw90bbxzhlvw5smm0vi-work …
```
=> fix cachix

buildbot_nix/__init__.py
- Allow pull requests to create output paths
Previously, it was not possible to get unmerged pull request outputs. I would like to access these (e.g. for hosting a preview version of a website in a similar way to https://docs.netlify.com/site-deploys/deploy-previews/ or https://vercel.com/docs/deployments/preview-deployments)
These are now surfaced under `{owner}/{repo}/pulls/{pr number}`
- Fix repository attribute name conflicts
Previously there was no difference between samely-named attributes in different repositories.
This has been changed so outputs are under `{owner}/{repo}/{branch}`
- Allow full attribute names, still stripping path traversal
Previously, presumably to prevent path traversal, if your attribute name contained slashes buildbot-nix would only take the last segment as …
=> feat!: Update output path writing

buildbot_nix/models.py
See #285 for context. I tested both Cachix and a custom step to work properly, see [buildbot my instance](https://buildbot.redalder.org/#/builders/56/builds/91).
=> Fix being unable to declare custom `PostBuildStep`s from Nix

buildbot_nix/__init__.py
Always reports the combined `nix-build` build report, even with individual builds, closes #279, see image:
=> Always report `nix-build`, even with individual build reports

buildbot_nix/__init__.py, buildbot_nix/failed_builds.py
Closes #280, currently a draft because it doesn't yet output a clickable link, it merely just dumps a link into the textual output of the cached failed build, see image:
Next I will attempt to add a clickable link using HTML.
=> Remember first failed build URL and display it in cached failures

buildbot_effects/__init__.py, buildbot_nix/__init__.py, buildbot_nix/models.py, nix/buildbot-effects.nix, nix/checks/effects.nix, nix/master.nix
This PR to another PR (sorry for the complexity) is what I use currently to build and deploy my flake-based personal system configuration. This holds all the changes I had to make to get `flyctl deploy` working for docker images built in my flake:
* Add `/var/tmp` as a tmpfs mount point in the bwrapped effects runner
* Flush at the end of writing secrets.json before passing it to `bwrap` (otherwise that file would be empty, thanks python buffering).
* Make per-repo secrets configurable and pass those through from the nix config to the buildbot master plugin, to each worker, and pick that up in the buildbot_effects commandline invocation.
With these changes, I have successfully run a flyctl deploy with the access token sourced from secrets passed in on that per-repo basis.
=> Secrets for hercules-ci style effects

flake.nix, nix/checks/flake-module.nix
This enables the dev shell & corresponding dev tools on recent macs, which happens to be the machine type I'm using (-:
=> Add aarch64-darwin to systems the flake cares about

.gitignore, buildbot_nix/__init__.py, buildbot_nix/github_projects.py, buildbot_nix/models.py, buildbot_nix/nix_status_generator.py, buildbot_nix/oauth2_proxy_auth.py, buildbot_nix/repo_config/__init__.py, nix/treefmt/flake-module.nix, pyproject.toml
```python
class A:
def foo(a: int) -> int:
return a
class B:
def foo(b: int, a: int) -> int: # this line will throw a type error
return b + super().foo(a)
```
=> Actually enable `mypy`

buildbot_nix/buildbot_nix/oauth2_proxy_auth.py
Setting up buildbot-nix with oauth2-proxy gives error:
```
buildbot_nix/oauth2_proxy_auth.py", line 25, in __init__
twistd[708]: if self.user_info_provider is None:
twistd[708]:     builtins.AttributeError: 'OAuth2ProxyAuth' object has no attribute 'user_info_provider'
```
There is also an issue that the user isn't granted 'admins' role if user_info_provider is used instead of userInfoProvider.
=> OAuth2ProxyAuth: initializing AuthBase.userInfoProvider

nix/worker.nix
trace: Obsolete option `services.buildbot-nix.worker.package' is used ...
=> nix/worker: update trace for buildbot-nix.packages

buildbot_nix/buildbot_nix/__init__.py
Without this property gcroots wouldn't get created and thanks to `getProperty` silently failing.
=> Set `default_branch` property

buildbot_nix/buildbot_nix/repo_config/__init__.py
Seems like there was a bug there all along, without this the repository config system wouldn't ever trigger.
=> Fix repository configuration not being recognized

buildbot_nix/buildbot_nix/__init__.py
For nix we don't depend really on interesting environment variables.
This reduces some noice from the log.
=> don't log environment for evaluation and building

buildbot_effects/buildbot_effects/__init__.py
https://github.com/hercules-ci/hercules-ci-agent/blob/cae08186393d9736f2b3a5d30b2c7efe5569e337/hercules-ci-agent/src/Hercules/Effect.hs
The socket handling in hercules isn't simple, not sure if any more of it is necessary here.
=> buildbot_effects: bind nix daemon socket, set NIX_REMOTE

nix/checks/flake-module.nix, nix/master.nix
Using https://nixos.org/manual/nixpkgs/stable/#opt-allowAliases means that all mentions of `pkgs.hostPlatform` will fail to evaluate since `pkgs.hostPlatform` is a alias see https://github.com/NixOS/nixpkgs/blob/6fa3bffe7919b63d9fbd32cee9bde440f3e180ab/pkgs/top-level/aliases.nix#L1668
=> fix: nixpkgs no aliases

buildbot_effects/buildbot_effects/__init__.py
Instead of doing Popen with a piped stderr / stdin and then reading/printing what we read, let's instead just hand the existing stdout/err through to the spawned process. It saves complexity and ensures that no IO buffering messes up line-wise output.
In my tests, this fixes #406, resulting in an acceptable logline-streaming cadence (about 2 or three at a time instead of batches of 50).
=> buildbot-effects: Don't manually handle stdout/err

buildbot_nix/buildbot_nix/__init__.py, buildbot_nix/buildbot_nix/models.py, flake.nix, nix/cachix.nix, nix/lib.nix, nix/master.nix
This PR untangles configuration of the cachix cache slightly, removing the special python code for it and setting the equivalent configuration all up in nix. Also, it uses the opportunity to group all cachix-related configuration into a single mkMerged block in master.nix and refactors the flake's `lib` export such that it can be used inside master.nix.
=> Rewrite cachix config as pure nix

buildbot_effects/buildbot_effects/__init__.py, buildbot_nix/buildbot_nix/worker.py
Error started with 2.24 -> 2.28 nix bump. https://github.com/nix-community/infra/pull/1768#issuecomment-2788784442
Looks like it is from https://github.com/NixOS/nix/commit/a03bb4455cee010bbfcf7e322b10ec7e35123032.
```
Couldn't execute /bin/sh -c "echo started": No such file or directory
```
=> buildbot_effects: bind /bin/sh

flake.nix, nix/flake-module.nix, nix/lib.nix
This seems to have gotten dropped in #429, but it's part of the exported interface by now (and I use & need it for accessing my attic cache).
This PR adds back the `lib` flake attribute, and the `interpolate` attribute; this time it includes documentation (in nix-community/nixdoc format).
=> Add lib.interpolate function back

packages/buildbot.nix
On 4.2.* deprecation warnings cause exceptions instead of just being logged, this was fixed in 4.3.
=> add patch to fix deprecation warnings

buildbot_nix/buildbot_nix/__init__.py
When a user triggers a rebuild for a cached failure, this runs on one of the `SKIPPED_BUILDER_NAMES` workers which I believe don't have a proper PATH and end up failing because the worker can't find the nix binary. You can see one such failed rebuild [in the NGI buildbot here](https://buildbot.ngi.nixos.org/#/builders/936/builds/483).
In order to keep the skipped builders setup as simple as possible, I've opted to add a trigger for a complete `nix-eval` in such cases (which should go to our regular builders). Running just `nix-build` could fail if drvs had been GC'ed (or I guess with multiple workers and not a singular cache).
I'm not sure if there's a better way to do this in buildbot, if there are better ideas let me know and I can try to implement them. The current implementation works …
=> Rebuild cached failures on proper workers
